//category
export const FETCH_CATEGORY = "FETCH_CATEGORY";
// product 
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS"; 
export const FETCH_PRODUCT_BY_ID= "FETCH_PRODUCT_BY_ID"; 
//auth 
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const EDIT_SHOPPING_LIST= "EDIT_SHOPPING_LIST"; 
export const EDIT_WISH_LIST= "EDIT_WISH_LIST"; 
export const EDIT_PROFILE = "EDIT_PROFILE"; 
export const DELETE_WISHLIST= "DELETE_WISHLIST" ; 
